server:
  port: 10001
  servlet:
    session:
      timeout: 60000m

spring:
  application:
    name: gulimall-product
  datasource:
    username: root
    password: 7410852963w
    url: jdbc:mysql://175.178.212.59:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:templates/,classpath:static/

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: --
      secret-key: --
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
    sentinel:
      transport:
        dashboard: localhost:8080

  #  alibaba.cloud.access-key=your-ak
  #  alibaba.cloud.secret-key=your-sk
  #  alibaba.cloud.oss.endpoint=***

  #    sentinel:
  redis:
    host: 175.178.212.59
    port: 6379
    timeout: 80000ms

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true
  client:
    config:
      default: #这里就是指的所有被加载的默认FeignClient实现的服务配置都生效
        connectTimeout: 1110000
        readTimeout: 1110000

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  #关闭thymeleaf缓存
  thymeleaf:
    cache: false

  session:
    store-type: redis

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  #设置实体类的自增主键
  global-config:
    db-config:
      id-type: auto
      #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
