server:
  port: 10001
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: gulimall-product
  datasource:
    username: root
    password: root
    url: jdbc:mysql://175.178.212.59:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:templates/,classpath:static/

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: LTAI5t95sFwNdrGuoy2FMJtR
      secret-key: VhLu77rWpm74QefRuJn7mlxsVcDq8Z
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com

  #  alibaba.cloud.access-key=your-ak
#  alibaba.cloud.secret-key=your-sk
#  alibaba.cloud.oss.endpoint=***

  #    sentinel:
#      transport:
#        #配置sentinel dashboard地址
#        dashboard: localhost:8080

#  redis:
#    host: 192.168.77.130
#    port: 6379

#开启feign对sentinel的支持
#feign:
#  sentinel:
#    enabled: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  #关闭thymeleaf缓存
  thymeleaf:
    cache: false
#    prefix:
  redis:
    host: 175.178.212.59
    port: 6379

  session:
    store-type: redis

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  #设置实体类的自增主键
  global-config:
    db-config:
      id-type: auto
      #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.spower.gulimall: debug


#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'