server:
  port: 20000
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8666
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719

  redis:
    host: 175.178.212.59
    port: 6379

  session:
    store-type: redis
  #服务追踪
  zipkin:
    base-url: http://175.178.212.59:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

feign:
  client:
    config:
      default:
        #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        ConnectTimeOut: 15000
        #指建立连接后从服务端读取到可用资源所用的时间
        ReadTimeOut: 15000

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'