server:
  port: 20000
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 175.178.212.59
    port: 6379

  session:
    store-type: redis


feign:
  client:
    config:
      default:
        #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        ConnectTimeOut: 15000
        #指建立连接后从服务端读取到可用资源所用的时间
        ReadTimeOut: 15000