server:
  port: 25000

spring:
  application:
    name: gulimall-seckill-server

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8666
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719
  #配置异步任务线程池
  task:
    execution:
      pool:
        core-size: 5
        max-size: 50

##开启feign对sentinel的支持(降级熔断)
feign:
  sentinel:
    enabled: true

  session:
    store-type: redis

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
